[patterns]
bitcoin = '(cryptocurrenc(ies|y)|b(i|ut)tcoin|ethereum|dogecoin|\bbtc\b|\beth\b|blockchain)'
lisp = '\b(scheme|clojure(script)?|e?lisp[sy]?|racket|hy|guile|haskell|urn)\b'
naked = 'n(ud(es?|ity)|ake(d(ness)?|e|y)|sfw)'
python = 'python(ic|ista)?'
fuck = '(#?[\w-]*f+u+(cc|c+k|q|k\b|kk)[\w-]*)'
bots = '\bbot(s|ally)?\b'
art = '\b(art(ist(ic)?|s(y)?)?|music((al)?s?|ians?)?|craft(s|y|er|ing)?)\b'
tilde = '\btilde(s)?\b'
dnd = '\bd(ungeons)?( (&|and) |&|n)d(ragons)?\b'
mastodon = '\b(masto(don)?|pleroma|pixelfed|activitypub|fed(eration|i(verse)?))\b'
cats = '\b(cats?|kitt(en|ies|y))\b'
birds = '\b(bir(b|d)(y|ie)?s?)\b'
butts = '\b(b(utts?|oot(y|ies))|ass(es)?)\b'
pokemon = '\bp+o+k(e|é)+m+(o|a)+n+s*\b'
dogs = '\b(dog(g(o|y|ie))?s?|pup(p(y|ie|er))?s?)\b'
programming = '\b(scheme|clojure(script)?|e?lisp[sy]?|racket|hy|guile|haskell|urn|python(ic|ista)?|rust(\-lang)?|c|c#|c\+\+|golang|java(script)?|html|css|assembly|program(mer|ming|s)?|cod(e|er|ing))\b'
hackers = '\bhack(s|ers?|ed|ing)?\b'
covid = '\b((co)?rona(virus)?|covid(19)?)\b'
cannabis = '\b(weed|bong|canna(bis)?|420|blaze(it)?|hemp|indica|sativa)\b'
thicc = '([\w-]*t+h+i+(cc|c+k|q|k\b|kk)[\w-]*)'
pizza = '\bpizza\b'
