[patterns]
"bitcoin.json" = '(cryptocurrenc(ies|y)|bitcoin|ethereum|dogecoin|\bbtc\b|\beth\b|blockchain)'
"lisp.json" = '\b(scheme|clojure(script)?|e?lisp[sy]?|racket|hy|guile|haskell|urn)\b'
"naked.json" = 'n(ud(es?|ity)|ake(d(ness)?|e|y)|sfw)'
"python.json" = 'python(ic|ista)?'
"fuck.json" = '(#?[\w-]*f+u+(cc|c+k|q|k\b|kk)[\w-]*)'
"bots.json" = '\bbot(s|ally)?\b'
"art.json" = '\b(art(ist(ic)?|s(y)?)?|music(a(in|l(s)?){1})?)\b'
"tilde.json" = '\btilde(s)?\b'
"dnd.json" = '\bd(ungeons)?( (&|and) |&|n)d(ragons)?\b'
"mastodon.json" = '\b(masto(don)?|pleroma|pixelfed|activitypub|fed(eration|i(verse)?))\b'
